### ISSUE TITLE
check in all branch ..

### ISSUE THREAD

**Issue by Rachinvashihtsha** [suraj-k/suraj-rajput#1]
check in all branch ..master or origin branch should be empty ...

**Comment by suraj-k** [comment]
https://github.com/suraj-k/suraj-rajput/branches
sir 

master or origin branch empty

**Comment by Rachinvashihtsha** [comment]
u have deleted origin / master branch ... why ???????????????

i have advice you it should empy not delete ....

**Comment by Rachinvashihtsha** [comment]
make as master branch as default branch .

**Comment by Rachinvashihtsha** [comment]
commit data on all demo branch ::
